### ISSUE TITLE
Scalar inaccurate results

### ISSUE THREAD

**Issue by xsacha** [searchivarius/BlogCode#4]
I found the code as-is produced inaccurate results that weren't seen in real world testing.
To produce a more real-world result, I threw random numbers in using time(NULL), which prevented the scalar version being pre-optimised by the compiler but made the other versions unaffected.

In addition, the scalar version is in fact using vpermilps under the hood, as confirmed by GodBolt. If you reproduce this intrinsic shown in GodBolt you will get the same performance as the scalar version.

**Comment by searchivarius** [comment]
@xsacha could you be more precise? What do you refer to? There have been quite a few benchmarks posted in this blog. Thanks!

**Comment by xsacha** [comment]
Sorry, it was this one:
https://github.com/searchivarius/BlogCode/tree/master/2016/bench_sums

**Comment by searchivarius** [comment]
@xsacha how exactly do you add random?

**Comment by xsacha** [comment]
The fastest way to add a number that the compiler won't optimise away is to add time(NULL).

For example, where you set the input:
`      __m128 inp = _mm_set_ps(k, k + 1, k + 2, k + 3);`
change to:
`      __m128 inp = _mm_set_ps(k, k + time(NULL), k + 2, k + time(NULL));`

rand() or similar work too.

**Comment by xsacha** [comment]
Also, this is what GodBolt translated the scalar version of AVX to:

C++:
```C++
inline float mm256_sum1(__m256 reg) {
  float PORTABLE_ALIGN16 TmpRes[8];
  _mm256_store_ps(TmpRes, reg);
  return TmpRes[0] + TmpRes[1] + TmpRes[2] + TmpRes[3] +
         TmpRes[4] + TmpRes[5] + TmpRes[6] + TmpRes[7];
};
```

Assembly:
```asm
  vextractf128 xmm1, ymm0, 1
  vaddps ymm0, ymm0, ymm1
  vpermilpd xmm1, xmm0, 1 # xmm1 = xmm0[1,0]
  vaddps ymm0, ymm0, ymm1
  vhaddps ymm0, ymm0, ymm0
```

**Comment by searchivarius** [comment]
@xsacha this is great, I will have to update the blog, many thanks. However, I think I still need to check a few things. In particular, I don't understand how randomization helps : ok, if we get optimized SIMD code for an apparently "scalar" version, why would change in the data affect results? Randomization would only matter IMHO, if the compiler can compile the result all in advance. I also tried to compiled with ``-msse2``, but the scalar version was still faster (vpermilpd is an AVX command).

**Comment by xsacha** [comment]
That's exactly it, it is generating the result in advance. With the scalar version, the compiler is smart enough to precalculate the answer.

The code generation only matters after removing predictability.

**Comment by searchivarius** [comment]
HI @xsacha thanks a lot of pointing it out. I think my older results were for older compilers and the whole issue needs to be revisited someday. However, for now, I have just modified the blog post to let the reader know the benchmark is likely inaccurate.
